Update lint

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -39,4 +39,10 @@ jobs:
       - name: setup revive
         run: go install github.com/mgechev/revive@latest
       - name: lint
-        run: revive -exclude "plz-out/..."  -config ./config.toml -formatter default ./...
+        run: |
+          revive -exclude "plz-out/..." -config ./config.toml -formatter default ./... &2>1 revive_report.txt \
+          G_PROBLEMS=$( egrep -v "$(date +%Y/%m/%d)" $REVIVE_REPORT_FILE | wc -l ) \
+          if [[ "$G_PROBLEMS" -gt 0 ]]; then \
+            echo -e "\033[0;31mError. Number of problems ($G_PROBLEMS) exceeded acceptable value of 0" \
+            exit 1 \
+          fi
